### ISSUE TITLE
Kann niemanden mehr anmelden, wenn "Einladungslinks freischalten" ausgehakt ist

### ISSUE THREAD

**Issue by AlexanderGabriel** [open-event-manager/open-event-manager#58]
Wenn ich bei einem Termin "Einladungslinks freischalten" ausschalte sehe ich die Termine in der Kalenderübersicht zwar noch aber wenn ich dann auf den Termin drücke kommt diese URL: https://eventmanager/join?snack=Fehler,%20Bitte%20kontrollieren%20Sie%20ihre%20Daten.&color=danger und der Fehler "Keine öffentlichen Veranstaltungen geplant"

**Comment by h2Entwicklung** [comment]
@AlexanderGabriel 
Das ist auch korrekt. Nur wenn die Einladungslinks eingeschaltet sind, kann sich jemand öffentlich registrieren.
Somit ist die der Kombi, eine die Veranstaltung wird öffentlich angezeigt aber es kann sich nicht angemeldet möglich. Sollen wir das noch anpassen? Dann wäre quasi die Einladungslink-Checkbox der Masterhaken und die anderen Checkboxen werden erst sichtbar wenn die Checkbox mit den EInladungslinks angezeigt werden.

**Comment by AlexanderGabriel** [comment]
jupp. Bitte wie besprochen die Felder ausblenden, damit Termin ohne Link gar nicht auf dem Kalender sichtbar sind. Dann kommt auch kein Fehler mehr.
Dankeschön.
